// Card database for the game

const blackCards = [
  { id: 1, text: "What is the best thing about being a kid?", pick: 1 },
  { id: 2, text: "I never understood _____ until I tried it.", pick: 1 },
  { id: 3, text: "What's the secret to a happy life?", pick: 1 },
  { id: 4, text: "Life would be so much better if we had _____.", pick: 1 },
  { id: 5, text: "The worst part of waking up is _____.", pick: 1 },
  { id: 6, text: "What always makes me laugh?", pick: 1 },
  { id: 7, text: "If I could have any superpower, it would be _____.", pick: 1 },
  { id: 8, text: "The most embarrassing thing that happened to me was _____.", pick: 1 },
  { id: 9, text: "What's the best way to spend a rainy day?", pick: 1 },
  { id: 10, text: "My guilty pleasure is _____.", pick: 1 },
  { id: 11, text: "What would make the perfect vacation?", pick: 1 },
  { id: 12, text: "The next big trend will be _____.", pick: 1 },
  { id: 13, text: "What's the cure for boredom?", pick: 1 },
  { id: 14, text: "I would never leave home without _____.", pick: 1 },
  { id: 15, text: "What makes the best midnight snack?", pick: 1 },
  { id: 16, text: "_____ + _____ = The perfect weekend.", pick: 2 },
  { id: 17, text: "I got in trouble for bringing _____ to school.", pick: 1 },
  { id: 18, text: "The new Olympic sport should be _____.", pick: 1 },
  { id: 19, text: "What did I find under my bed?", pick: 1 },
  { id: 20, text: "What's the worst birthday gift ever?", pick: 1 },
  { id: 21, text: "My new band is called _____.", pick: 1 },
  { id: 22, text: "What's the most overrated thing?", pick: 1 },
  { id: 23, text: "I can't believe I spent money on _____.", pick: 1 },
  { id: 24, text: "What's impossible to do with a straight face?", pick: 1 },
  { id: 25, text: "The movie of my life would be called _____.", pick: 1 },
];

const whiteCards = [
  { id: 1, text: "Pizza for breakfast" },
  { id: 2, text: "Unlimited WiFi" },
  { id: 3, text: "Talking to plants" },
  { id: 4, text: "Really loud sneezing" },
  { id: 5, text: "Finding money in old jeans" },
  { id: 6, text: "Dancing like nobody's watching (but they are)" },
  { id: 7, text: "Staying up past your bedtime" },
  { id: 8, text: "A really good sandwich" },
  { id: 9, text: "Forgetting why you walked into a room" },
  { id: 10, text: "The perfect nap" },
  { id: 11, text: "Ice cream for dinner" },
  { id: 12, text: "Texting the wrong person" },
  { id: 13, text: "Trying to look cool" },
  { id: 14, text: "Breaking into spontaneous song" },
  { id: 15, text: "Pretending to be busy" },
  { id: 16, text: "Unlimited snacks" },
  { id: 17, text: "A really good hair day" },
  { id: 18, text: "Binge-watching your favorite show" },
  { id: 19, text: "Overthinking everything" },
  { id: 20, text: "Laughing at your own jokes" },
  { id: 21, text: "Hitting the snooze button" },
  { id: 22, text: "Finding the perfect parking spot" },
  { id: 23, text: "A pet rock" },
  { id: 24, text: "Talking to yourself" },
  { id: 25, text: "Wearing pajamas all day" },
  { id: 26, text: "Instant ramen" },
  { id: 27, text: "Getting caught singing in the shower" },
  { id: 28, text: "A warm blanket" },
  { id: 29, text: "Eating cookies straight from the package" },
  { id: 30, text: "Playing video games" },
  { id: 31, text: "Telling really bad jokes" },
  { id: 32, text: "A lazy Sunday" },
  { id: 33, text: "Checking the fridge 10 times" },
  { id: 34, text: "Making weird faces in the mirror" },
  { id: 35, text: "A bouncy castle" },
  { id: 36, text: "Procrastination" },
  { id: 37, text: "Drawing mustaches on photos" },
  { id: 38, text: "A bubble bath" },
  { id: 39, text: "Googling yourself" },
  { id: 40, text: "Building pillow forts" },
  { id: 41, text: "Free samples at the grocery store" },
  { id: 42, text: "Matching socks" },
  { id: 43, text: "A surprise party" },
  { id: 44, text: "Walking into a spider web" },
  { id: 45, text: "Trying to act natural" },
  { id: 46, text: "Collecting random things" },
  { id: 47, text: "A really good high five" },
  { id: 48, text: "Taking selfies" },
  { id: 49, text: "Getting lost in your own neighborhood" },
  { id: 50, text: "Eating dessert first" },
  { id: 51, text: "A spontaneous road trip" },
  { id: 52, text: "Trying a new recipe and failing" },
  { id: 53, text: "Sleeping in" },
  { id: 54, text: "Feeding ducks at the park" },
  { id: 55, text: "A treasure map" },
  { id: 56, text: "Learning a magic trick" },
  { id: 57, text: "Karaoke night" },
  { id: 58, text: "Cloud watching" },
  { id: 59, text: "Making up your own handshake" },
  { id: 60, text: "A lucky penny" },
  { id: 61, text: "Telling ghost stories" },
  { id: 62, text: "A mystery box" },
  { id: 63, text: "Having no plans" },
  { id: 64, text: "Winning an argument in your head" },
  { id: 65, text: "A cardboard box" },
  { id: 66, text: "Wrapping yourself in a burrito blanket" },
  { id: 67, text: "A secret handshake" },
  { id: 68, text: "Jumping in puddles" },
  { id: 69, text: "Finding a four-leaf clover" },
  { id: 70, text: "Having a picnic" },
  { id: 71, text: "Making up stories" },
  { id: 72, text: "A time machine" },
  { id: 73, text: "Reading comics" },
  { id: 74, text: "Flying a kite" },
  { id: 75, text: "A rainbow" },
  { id: 76, text: "Exploring the attic" },
  { id: 77, text: "Making snow angels" },
  { id: 78, text: "A camping adventure" },
  { id: 79, text: "Stargazing" },
  { id: 80, text: "Building a sandcastle" },
];

function shuffleArray(array) {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

module.exports = {
  blackCards,
  whiteCards,
  shuffleArray,
};
